### PR TITLE
fix wrong check actionEnabled

### PR DESCRIPTION
**Pull request by maxinminax**
https://github.com/moleculerjs/database/issues/12

### CODE REVIEW

**Comment by vimalraj-a** [comment]
@icebob Can this PR be approved? Current code of `actionEnabled` is creating problem in our project where we customized the rest end points for default actions.

Since there is no npm package for this, we are kind of stuck.

**Comment by vimalraj-a** [comment]
@icebob Can this PR be merged ?

**Comment by AndreMaz** [comment]
Hi @maxinminax icebob took a few days off and I don't have enough context about the issue so I can't merge it.

However, you can use the fix by installing it via `npm i https://github.com/maxinminax/database`

**Review by icebob — APPROVED** [review]
Thanks. Sorry for late

**Pull request merged**
